# Generated by Django 6.1.1 on 2026-09-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', '000 – Generalidades e Informação'), ('100', '100 – Filosofia e Psicologia'), ('200', '200 – Religião e Teologia'), ('300', '300 – Ciências Sociais e Direito'), ('400', '400 – Linguística e Idiomas'), ('500', '500 – Ciências Puras (Exatas e Naturais)'), ('600', '600 – Ciências Aplicadas (Tecnologia)'), ('700', '700 – Artes e Recreação'), ('800', '800 – Literatura'), ('900', '900 – História e Geografia')], default='000', max_length=3, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('Físico', 'Físico'), ('Digital', 'Digital')], default='Físico', max_length=10, verbose_name='Tipo de Acervo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
