# Generated by Django 6.1.1 on 2026-09-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_remove_livro_ano_remove_livro_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('0', '0 – Generalidades e Informação'), ('1', '1 – Filosofia e Psicologia'), ('2', '2 – Religião e Teologia'), ('3', '3 – Ciências Sociais e Direito'), ('4', '4 – Linguística e Idiomas'), ('5', '5 – Ciências Puras (Exatas e Naturais)'), ('6', '6 – Ciências Aplicadas (Tecnologia)'), ('7', '7 – Artes e Recreação'), ('8', '8 – Literatura'), ('9 ', '9– História e Geografia')], default='000', max_length=3, verbose_name='Categoria'),
        ),
    ]
